<template>

  <Title title="Posilování"/>
  <Categories @changeCat="active = $event" :cat_array="categories"/>
  <Videos :videos_array="videos" :active_cat="active"/>

</template>

<script>

import Title from '@/components/Title.vue'
import Categories from '@/components/Categories.vue'
import Videos from '@/components/Videos.vue'

export default {
  name: "Posilovani Page",
  components: {
    Title,
    Categories,
    Videos
  },
  data() {
    let vse = "Vše";
    let nacini = "S náčiním";
    let ostatni = "Ostatní pomůcky";
    let vaha = "S vlastní vahou";
    let nizka = require("@/assets/obt_1.svg");
    let stredni = require("@/assets/obt_2.svg");
    let vysoka = require("@/assets/obt_3.svg");
    return {
      active: vse,
      categories: [vse, nacini, vaha, ostatni],
      videos: [
        {
          title: "Posilování 1",
          description: "Posilování s vlastní vahou",
          time: 10,
          image: require("@/assets/posilovani/Posilování_1.jpg"),
          linkTrenerska: "https://youtu.be/rsvkGeQh9NM",
          linkDlouha: "https://youtu.be/RhmpnsOYBFQ",
          category: vaha,
          difficulty: stredni,
        },
        {
          title: "Posilování 2",
          description: "Posilování s míčem",
          time: 16,
          image: require("@/assets/posilovani/Posilování_2.jpg"),
          linkTrenerska: "https://youtu.be/dc_csJWGoVc",
          linkDlouha: "https://youtu.be/xwk_QVRtVD4",
          category: nacini,
          difficulty: stredni,
        },
        {
          title: "Posilování 3",
          description: "Posilování s vlastní vahou",
          time: 12,
          image: require("@/assets/posilovani/Posilování_3.jpg"),
          linkTrenerska: "https://youtu.be/MjL6yEdrDag",
          linkDlouha: "https://youtu.be/tjqcke126dc",
          category: vaha,
          difficulty: stredni,
        },
        {
          title: "Posilování 4",
          description: "Posilování s vlastní vahou",
          time: 15,
          image: require("@/assets/posilovani/Posilování_4.jpg"),
          linkTrenerska: "https://youtu.be/K5ae3qFpq2I",
          linkDlouha: "https://youtu.be/yuI4GbPlPik",
          category: vaha,
          difficulty: vysoka,
        },
        {
          title: "Posilování 5",
          description: "Posilování s gumou",
          time: 16,
          image: require("@/assets/posilovani/Posilování_5.jpg"),
          linkTrenerska: "https://youtu.be/5GGEW7-qt70",
          linkDlouha: "https://youtu.be/vk_qlk1pxRA",
          category: ostatni,
          difficulty: vysoka,
        },
        {
          title: "Posilování 6",
          description: "Posilování se židlí",
          time: 17,
          image: require("@/assets/posilovani/Posilování_6.jpg"),
          linkTrenerska: "https://youtu.be/3RO4NOTGlWI",
          linkDlouha: "https://youtu.be/dzlM2Vix4eY",
          category: ostatni,
          difficulty: vysoka,
        },
        {
          title: "Posilování 7",
          description: "Posilování s obručí",
          time: 12,
          image: require("@/assets/posilovani/Posilování_7.jpg"),
          linkTrenerska: "https://youtu.be/7lT_p33CSYQ",
          linkDlouha: "https://youtu.be/yrtKHQgDVk8",
          category: nacini,
          difficulty: nizka,
        },
        {
          title: "Posilování 8",
          description: "Posilování s vlastní vahou",
          time: 11,
          image: require("@/assets/posilovani/Posilování_8.jpg"),
          linkTrenerska: "https://youtu.be/vxm8ysyBiOo",
          linkDlouha: "https://youtu.be/srXEfcUrOM4",
          category: vaha,
          difficulty: nizka,
        },
        {
          title: "Posilování 9",
          description: "Posilování s podložkami",
          time: 11,
          image: require("@/assets/posilovani/Posilování_9.jpg"),
          linkTrenerska: "https://youtu.be/hodcQW1LQus",
          linkDlouha: "https://youtu.be/lcEUxweJk9Y",
          category: ostatni,
          difficulty: vysoka,
        },
        {
          title: "Posilování 10",
          description: "Posilování se švihadlem",
          time: 12,
          image: require("@/assets/posilovani/Posilování_10.jpg"),
          linkTrenerska: "https://youtu.be/Tzq9sHnPCso",
          linkDlouha: "https://youtu.be/tZ582JHLOSo",
          category: nacini,
          difficulty: nizka,
        },
        {
          title: "Posilování 11",
          description: "Posilování s vlastní vahou",
          time: 16,
          image: require("@/assets/posilovani/Posilování_11.jpg"),
          linkTrenerska: "https://youtu.be/RIkO0PDxdfE",
          linkDlouha: "https://youtu.be/lF-vW4Gd6WQ",
          category: vaha,
          difficulty: stredni,
        },
        {
          title: "Posilování 12",
          description: "Posilování s gumou a zátěžemi",
          time: 15,
          image: require("@/assets/posilovani/Posilování_12.jpg"),
          linkTrenerska: "https://youtu.be/ozSrN9PL5NM",
          linkDlouha: "https://youtu.be/IZs7Malwknc",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 13",
          description: "Posilování s kužely",
          time: 12,
          image: require("@/assets/posilovani/Posilování_13.jpg"),
          linkTrenerska: "https://youtu.be/JRVWDIAAOpk",
          linkDlouha: "https://youtu.be/2GRTanYKBHM",
          category: nacini,
          difficulty: nizka,
        },
        {
          title: "Posilování 14",
          description: "Posilování se zátěžemi",
          time: 20,
          image: require("@/assets/posilovani/Posilování_14.jpg"),
          linkTrenerska: "https://youtu.be/E6RnzkzJJsg",
          linkDlouha: "https://youtu.be/_BGk4yAQVqA",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 15",
          description: "Posilování s vlastní vahou",
          time: 14,
          image: require("@/assets/posilovani/Posilování_15.jpg"),
          linkTrenerska: "https://youtu.be/lY3f0CwtYXc",
          linkDlouha: "https://youtu.be/oVtH8d8UOhY",
          category: vaha,
          difficulty: nizka,
        },
        {
          title: "Posilování 16",
          description: "Posilování s míčem",
          time: 9,
          image: require("@/assets/posilovani/Posilování_16.jpg"),
          linkTrenerska: "https://youtu.be/agf2zCAzmu4",
          linkDlouha: "https://youtu.be/30vEia9NE8k",
          category: nacini,
          difficulty: nizka,
        },
        {
          title: "Posilování 17",
          description: "Posilování s gumou",
          time: 13,
          image: require("@/assets/posilovani/Posilování_17.jpg"),
          linkTrenerska: "https://youtu.be/kvkJ-BxE1Ts",
          linkDlouha: "https://youtu.be/wyyboVAd1UQ",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 18",
          description: "Posilování s podložkami",
          time: 16,
          image: require("@/assets/posilovani/Posilování_18.jpg"),
          linkTrenerska: "https://youtu.be/EbLx0TbRxV8",
          linkDlouha: "https://youtu.be/6lnu3KFctUg",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 19",
          description: "Posilování s tenisovými míčky",
          time: 10,
          image: require("@/assets/posilovani/Posilování_19.jpg"),
          linkTrenerska: "https://youtu.be/kKmQ8sT9CLc",
          linkDlouha: "https://youtu.be/QgnA8vKgp4M",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 20",
          description: "Posilování s gumou",
          time: 15,
          image: require("@/assets/posilovani/Posilování_20.jpg"),
          linkTrenerska: "https://youtu.be/s5VYXhSaTsI",
          linkDlouha: "https://youtu.be/ylG47-V3GHs",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 21",
          description: "Posilování s gumou a podložkami",
          time: 13,
          image: require("@/assets/posilovani/Posilování_21.jpg"),
          linkTrenerska: "https://youtu.be/RtZkG5Yasp4",
          linkDlouha: "https://youtu.be/5WAJfZwEPVU",
          category: ostatni,
          difficulty: vysoka,
        },
        {
          title: "Posilování 22",
          description: "Posilování s velkým míčem",
          time: 10,
          image: require("@/assets/posilovani/Posilování_22.jpg"),
          linkTrenerska: "https://youtu.be/yNwdwEFdrd0",
          linkDlouha: "https://youtu.be/blKf-HRegnc",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 23",
          description: "Posilování s flaškami",
          time: 10,
          image: require("@/assets/posilovani/Posilování_23.jpg"),
          linkTrenerska: "https://youtu.be/I5RaSjZuYjY",
          linkDlouha: "https://youtu.be/7zOMi9rVUQM",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 24",
          description: "Posilování se švihadlem",
          time: 7,
          image: require("@/assets/posilovani/Posilování_24.jpg"),
          linkTrenerska: "https://youtu.be/sfliNumFEWs",
          linkDlouha: "https://youtu.be/bwG6nr2Ratc",
          category: nacini,
          difficulty: stredni,
        },
        {
          title: "Posilování 25",
          description: "Posilování s míčem",
          time: 10,
          image: require("@/assets/posilovani/Posilování_25.jpg"),
          linkTrenerska: "https://youtu.be/7gyvfXFTwdA",
          linkDlouha: "https://youtu.be/gZImjF1D60s",
          category: nacini,
          difficulty: stredni,
        },
        {
          title: "Posilování 26",
          description: "Posilování ve dvojici s pomůckami",
          time: 12,
          image: require("@/assets/posilovani/Posilování_26.jpg"),
          linkTrenerska: "https://youtu.be/hXojKCFqwjI",
          linkDlouha: "https://youtu.be/p21XEmc1W4s",
          category: ostatni,
          difficulty: stredni,
        },
        {
          title: "Posilování 27",
          description: "Posilování s vlastní vahou",
          time: 9,
          image: require("@/assets/posilovani/Posilování_27.jpg"),
          linkTrenerska: "https://youtu.be/ohpX57iTMF8",
          linkDlouha: "https://youtu.be/Ko5bewR1QGM",
          category: vaha,
          difficulty: nizka,
        },
        {
          title: "Posilování 28",
          description: "Posilování s vlastní vahou",
          time: 8,
          image: require("@/assets/posilovani/Posilování_28.jpg"),
          linkTrenerska: "https://youtu.be/Q3Y7-KYKz-Y",
          linkDlouha: "https://youtu.be/64gm2XrHtH4",
          category: vaha,
          difficulty: nizka,
        },
        {
          title: "Posilování 29",
          description: "Posilování se švihadlem",
          time: 9,
          image: require("@/assets/posilovani/Posilování_29.jpg"),
          linkTrenerska: "https://youtu.be/QJiIrFBTzjQ",
          linkDlouha: "https://youtu.be/dS_Br_AHuqE",
          category: nacini,
          difficulty: nizka,
        },
        {
          title: "Posilování 30",
          description: "Posilování s gumou",
          time: 8,
          image: require("@/assets/posilovani/Posilování_30.jpg"),
          linkTrenerska: "https://youtu.be/5ci4tXE6EdM",
          linkDlouha: "https://youtu.be/pYIGpanaxZY",
          category: ostatni,
          difficulty: nizka,
        },
      ]
    };
  },
};
</script>